---
name: 'PR Actions'

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: 'PR Actions'
    runs-on: ubuntu-latest

    steps:
      - name: 'Skip Duplicate Actions'
        uses: fkirc/skip-duplicate-actions@v3.4.0

      - name: 'Checkout Code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: "Set SHOULD_RUN flag"
        run: |
          if [[ "${{github.event.head_commit.message}}" =~ (skip\ ci|ci\ skip) ]]; then
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
          else
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
          fi

      - name: 'Set up Node'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        if: env.SHOULD_RUN == 'true'

      - name: 'Restore workspace cache'
        uses: actions/cache@v2
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-001-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-001-
        if: env.SHOULD_RUN == 'true'

      - name: 'Install Dependencies'
        run: yarn install --frozen-lockfile --non-interactive
        if: env.SHOULD_RUN == 'true'

      - name: 'Lint'
        run: yarn nx lint web
        if: env.SHOULD_RUN == 'true'

      - name: 'Test'
        run: yarn nx test web
        if: env.SHOULD_RUN == 'true'

      - name: 'Build'
        run: yarn nx build web --prod
        if: env.SHOULD_RUN == 'true'
